### ISSUE TITLE
Security Concern: Insecure Invitation Process Reveals GitHub Access Token

### ISSUE THREAD

**Issue by 0x30c4** [madewithai/madewithai#24]
**Description:**

I noticed a security issue with the invitation process on the [https://madewithai.netlify.app/](https://madewithai.netlify.app/) site. The site allows anyone to invite anyone, and upon inspecting the network activity, I discovered that a GitHub access token is exposed.

By using this token, I was able to change the organization's description successfully. This indicates that the token has broader permissions than necessary and is being exposed insecurely.

**Steps to Reproduce:**
1. Open the [https://madewithai.netlify.app/](https://madewithai.netlify.app/) site.
2. Initiate an invitation process.
3. Inspect the network tab in the browser's developer tools.
4. Notice the GitHub access token being exposed in the network request.
5. Use the exposed token to make API requests, such as changing the organization's description.

**Expected Behavior:**
- The GitHub access token should not be exposed in the client-side code or network requests.
- The token should have limited permissions, only sufficient for the invitation process.

**Recommendations:**
1. Create a GitHub token with the appropriate limited permissions required for sending invites.
2. Ensure the token is kept secure and not exposed in client-side code or network requests.
3. Review and update the invitation process to follow best practices for security.

**Comment by zackha** [comment]
Thank you, I will update the code again as soon as possible.

**Comment by zackha** [comment]
Hi @0x30c4,

Thank you so much for pointing out the security issue. I have reviewed and updated the code to ensure the GitHub access token is no longer exposed in client-side code or network requests. The invitation process is now more secure.

I am really grateful for your valuable feedback. If your GitHub Sponsorship is active, I would like to make a donation to show my appreciation for your help.

Thanks again and best regards!

**Comment by 0x30c4** [comment]
Hello @zackha,

Welcome, and thank you for your kind gesture. Unfortunately, GitHub sponsorship is not available in my region :/.
