### ISSUE TITLE
Unexpected invitation into the organization

### ISSUE THREAD

**Issue by phoe** [madewithai/madewithai#29]
Hi, got this in the mail today.

![Zrzut ekranu z 2024-06-26 09-24-39](https://github.com/madewithai/madewithai/assets/15045546/9e84ccdc-3fcc-469d-932a-3052e96f2ba0)

![Zrzut ekranu z 2024-06-26 09-20-57](https://github.com/madewithai/madewithai/assets/15045546/f121fcc8-6966-49e1-9149-96453a25040e)

I haven't ever heard of this project or organization. I haven't ever used AI for programming. Are your organization invitations also made with AI?

**Comment by zackha** [comment]
Hi @phoe,

I recently came across your impressive GitHub profile and your innovative Common Lisp projects. I am reaching out to invite you to join our organization, where we aim to share and promote tools developed using AI.

By sharing your tools through our platform, we believe we can provide valuable resources to those in need and enhance the reach of your work. Moreover, we are considering potential sponsorship opportunities based on your involvement with our organization.

We would be thrilled to have you on board and look forward to the possibility of collaborating with you.

Best regards,

**Comment by phoe** [comment]
Hi @zackha,

You don't know me, you've never contacted me before, you send me spam via GitHub's organization invitation system and you give me a generic corporate `I recently came across your impressive GitHub profile and your innovative ${LANG} projects. I am reaching out to invite you to join our organization, where we aim to share and promote tools developed using AI.` response when queried about it. Your organization does not even have a single Lisp project and you tell me nothing about how my "innovative Common Lisp projects" align with your goals.

I would be thrilled to have you accept my GitHub spam & abuse report.

**Comment by zackha** [comment]
Hi @phoe, 

Thank you for your recommendations, and I apologize for any inconvenience.

**Comment by phoe** [comment]
Hi @zackha,

One more recommendation: since I was notified that some other Lisp hackers I know also got similar invitations, please refer to the attached paper for a suggestion of getting more positive traction for your organization.

[mazieres-kohler.pdf](https://github.com/user-attachments/files/15984727/mazieres-kohler.pdf)

**Comment by zackha** [comment]
😊

**Comment by zackha** [comment]
Thanks for the tip, it is greatly appreciated.
